# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faedd50b0a6be11a618ab2e09f9aad1347675398f7d3c06fbd6c2b5de7c93e462ad1f91884086a3dba01daf5b85793c4699b1b107a1f837657557283ccd436b3
  darksky_key: <%= ENV["DARKSKY_KEY"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

test:
  secret_key_base: 1d907bafbcfe00565f6f92292cf13bbe5fc9dae8272a5038bf0938cce5c810024254c4400ccca99158bfcc607e53678937876d04cfc06402bb39c70df19832b7
  darksky_key: <%= ENV["DARKSKY_KEY"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  darksky_key: <%= ENV["DARKSKY_KEY"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
